pipeline
{
    agent any
    tools {
        maven 'Maven'
    }
    stages
    {
        stage('Code Checkout')
        {
            steps
            {
                git url: 'https://github.com/diptampaul/EdurekaIGP.git', branch: 'main'
            }
        }
        
        stage('Code Compile')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Unit Test')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'mvn test'
                }
            }
        }

        stage('Code packaging')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'mvn package'
                }
            }
        }
    }
}