pipeline
{
    agent any
    tools {
        maven 'Maven'
    }
    stages
    {
        stage('Code Checkout')
        {
            steps
            {
                git url: 'https://github.com/diptampaul/EdurekaIGP.git', branch: 'main'
            }
        }
        
        stage('Code Compile')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Unit Test')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'mvn test'
                }
            }
        }

        stage('Code packaging')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'mvn package'
                }
            }
        }

        stage('install docker using ansible')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'ansible-playbook docker.yaml || echo "Ansible playbook execution failed, continuing pipeline..."'
                }
            }
        }

        stage('Build Docker Image')
        {
            steps
            {
                dir('ABC Technologies') {
                    sh 'cp "$WORKSPACE/ABC Technologies/target/ABCtechnologies-1.0.war" ./abc.war'
                    sh 'docker build -t abc_tech:$BUILD_NUMBER .'
                    sh 'docker tag abc_tech:$BUILD_NUMBER jsachdev07/abc_tech:$BUILD_NUMBER'
                }
            }
        }

		// stage('Push Docker Image')
		// { 
		// 	steps
		// 	{   
		// 	    withDockerRegistry([ credentialsId: "dockerhub", url: "" ])
		// 	    {
		// 	       sh 'docker push jsachdev07/abc_tech:$BUILD_NUMBER'
		// 	    }
		// 	}
		// }

		stage('Deploy as container')
		{
			steps
			{
				sh 'docker run -itd -P jsachdev07/abc_tech:$BUILD_NUMBER'
			}
		}
    }
}